name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Create .env file
      uses: ozaytsev86/create-env-file@v1
      with:
        file-name: ".env"
        ENV_DEBUG: true
        ENV_PORT: 8000
        ENV_CACHE_TIME: 1200
        ENV_CACHE_TYPE: InMemory
    - name: check
      run: cat .env
       
    - name: Deploying to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env_file: ".env"